<script>
	import Prompt1 from '$lib/assets/Accessibility test ss/prompt1.png';
	import Prompt2 from '$lib/assets/Accessibility test ss/prompt2-1.png';
	import Prompt3 from '$lib/assets/Accessibility test ss/prompt3-2.png';
	import Prompt4 from '$lib/assets/Accessibility test ss/prompt4-1.png';
</script>

<h1>Accessibility Applied to ChatGPT</h1>
<div class="section">
	<div class="section-card">
		<h2>Research Goal</h2>
		<p>
			In this report, I will be examining how accessible code generated by ChatGPT can be, based on
			the WCAG guidelines. I'll be basing my findings off of a 0-6 scale that rates the
			accessibility of each output, giving up to 2 points for 3 different guideline standards.
		</p>
	</div>
	<div class="section-card">
		<h2>Tool Researched</h2>
		<p>
			ChatGPT is a well-known prompt-based A.I. that can do many things, generating code included.
			Even in my personal career, I have had times where I rely on it to find some solutions to an
			issue I might have. However, the internet is already a place where accessibility, despite
			being vital to some user's ability to use it, isn't always made a priority. The Web Content
			Accessibility Guidelines (WCAG) seeks to help resolve this by providing a clear list of things
			a website needs to be accessible. Therefore, I want to see how well ChatGPT can match these
			guidelines through different prompts.
		</p>
	</div>
	<div class="section-card">
		<h2>Implementation and Testing</h2>
		<p>To examine the accessibility of the generated code, I used this method:</p>
		<ol>
			<li>
				Start a new chat and <strong>ask ChatGPT to generate a homepage</strong> for a taco restaurant
			</li>
			<li>
				<strong>Put the resulting code into a file,</strong> inserting images where necessary
			</li>
			<li>
				<strong>Evaluate the code and page on a 0 to 6 scale,</strong> based off the following WCAG
				guidelines:
				<ul>
					<li>
						Guideline 1.3 : Ensure that information and structure can be separated from presentation
						<ul>
							<li>
								1 point if the content is consumable without the presentation but has less that 2
								issues (spacing is too wide between related text, contrast is too low, etc.), 2
								points for fully meeting the requirement
							</li>
						</ul>
					</li>
					<li>
						Guideline 2.1 : Make all functionality operable via a keyboard interface
						<ul>
							<li>
								1 point if the entire site can be navigated by keyboard but has less than 2 issues
								(excessive tabbing, invisible but focusable elements, etc.), 2 points for fully
								meeting the requirement
							</li>
						</ul>
					</li>
					<li>
						Guideline 2.4 : Provide mechanisms to help users find content, orient themselves within
						it, and navigate through it
						<ul>
							<li>
								1 point if the entire site has proper structure to help navigation but has less than
								2 issues (Multiple h1s, unordered heading tags, etc.), 2 points for fully meeting
								the requirement
							</li>
						</ul>
					</li>
				</ul>
			</li>
		</ol>
	</div>
</div>

<div class="section">
	<div class="section-card">
		<h2>Evaluation</h2>
		<p>
			<a href="https://github.com/ParkerNix/AccessibilityTestOutputs" target="_blank"
				>Link to output code</a
			> | The following section will cover each output and the evaluation it received:
		</p>
		<ol>
			<li>
				<strong>Prompt 1: Basic</strong> |
				<img src={Prompt1} alt="The resulting page for prompt 1" />
				<ul>
					<li>
						<strong>Prompt:</strong> Can you code out a homepage for a taco restaurant?
					</li>
					<li>
						<strong>Scores:</strong>
						<ul>
							<li>1.3: 2/2</li>
							<li>
								2.1: 0/2; Heading tags are not easily navigated to on keyboard, header and nav are
								separate but nav could be nested in header
							</li>
							<li>2.4: 1/2; Multiple h1s</li>
							<li><strong>Overall: 3/6</strong></li>
						</ul>
					</li>
				</ul>
			</li>
			<hr />
			<li>
				<strong>Prompt 2: Detailed</strong> |
				<img src={Prompt2} alt="The resulting page for prompt 2" />
				<ul>
					<li>
						<strong>Prompt:</strong> Can you code out a homepage for a taco restaurant that includes
						a navigation menu at the top, a hero image, a tagline, some images of the food, some words
						about what the restaurant is, and a contact us section?
					</li>
					<li>
						<strong>Scores:</strong>
						<ul>
							<li>
								1.3: 0/2 images overlap each other, textboxes are too wide making the edges hard to
								see
							</li>
							<li>2.1: 1/2 Heading tags are not easily navigated to on keyboard</li>
							<li>2.4: 2/2</li>
							<li><strong>Overall: 3/6</strong></li>
						</ul>
					</li>
				</ul>
			</li>
			<hr />
			<li>
				<strong>Prompt 3: Level AA</strong> |
				<img src={Prompt3} alt="The resulting page for prompt 2" />
				<ul>
					<li>
						<strong>Prompt:</strong> Can you code out a homepage for a taco restaurant that includes
						a navigation menu at the top, a hero image, a tagline, some images of the food, some
						words about what the restaurant is, and a contact us section?
						<strong>Please be sure to abide by WCAG level AA guidelines.</strong>
					</li>
					<li>
						<strong>Scores:</strong>
						<ul>
							<li>1.3: 1/2 Color contrast between nav bg color and main bg color is too low</li>
							<li>
								2.1: 1/2 Puts contact info in a list, somewhat unnecessary and causes extra words to
								be read
							</li>
							<li>2.4: 2/2</li>
							<li><strong>Overall: 4/6</strong></li>
						</ul>
					</li>
				</ul>
			</li>
			<hr />
			<li>
				<strong>Prompt 4: Level AAA</strong> |
				<img src={Prompt4} alt="The resulting page for prompt 2" />
				<ul>
					<li>
						<strong>Prompt:</strong> Can you code out a homepage for a taco restaurant that includes
						a navigation menu at the top, a hero image, a tagline, some images of the food, some
						words about what the restaurant is, and a contact us section?
						<strong>Please be sure to abide by WCAG level AAA guidelines.</strong>
					</li>
					<li>
						<strong>Scores:</strong>
						<ul>
							<li>
								1.3: 1/2 Contact form is in one line, but the message textarea should be on its own
								line to provide space
							</li>
							<li>2.1: 2/2</li>
							<li>2.4: 2/2</li>
							<li><strong>Overall: 5/6</strong></li>
						</ul>
					</li>
				</ul>
			</li>
		</ol>
		<hr />
		<p>Final average: 3.75/6</p>
	</div>
</div>

<div class="section">
	<div class="section-card">
		<h2>Conclusion</h2>
		<p>
			ChatGPT is not the best at accessibility without prompting. It missed some very basic things
			that are best practice, like not having more than one h1 tag. With prompting, however, the
			code was much better. It seems like the way to get it to give the most accessible code is to
			ask it to specifically follow WCAG level AAA guidelines, but you still have to look over the
			code and the resulting page to ensure that there are no issues, meaning that there is still a
			required human aspect to this process.
		</p>
	</div>
</div>
